# GitHub Pages 配置文件
title: Claude 4 彻底杀疯了！
description: 全面碾压 Deepseek V3、GPT-4.1，2025年AI编程界顶流明星
url: "https://xianyu110.github.io"
baseurl: "/claude.asia"

# SEO 优化
lang: zh-CN
author: Claude中国团队
keywords: Claude, AI, 人工智能, 聊天机器人, 中国, 镜像

# 插件配置
plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag

# 构建设置
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter: rouge

# 排除文件
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - vendor/

# 包含文件
include:
  - _pages

# 默认设置
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"